#!/bin/bash
green="\e[1;32m"
red="\e[1;31m"
nc="\e[0m"
echo -en "${green} #Architecture:${red}  `uname -a`\n"
echo -en "${green} #CPU physical:${red} `cat /proc/cpuinfo | grep "cpu cores	:"`\n"
echo -en "${green} #vCPU:${red} `cat /proc/cpuinfo | grep "cpu cores	:"`\n"
echo -en "${green} #Memory Usage:${red} `free -m | awk '$1=="Mem:" {print $3"/"$2"Mb"}'` (`free | awk '/Mem/{printf("%.2f%"), $3/$2*100}'`)\n"
echo -en "${green} #Disk Usage:${red} `df -PTh|egrep -iw "/home"|awk '{printf $4"/"$5" ("$6") "$7}'`\n"
echo -en "${green} #CPU load:${red} `cat /proc/stat| awk '/cpu/{printf("%.2f%\n"), ($2+$4)*100/($2+$4+$5)}'| awk '{print $0}' | head -1`\n"
echo -en "${green} #Last boot:${red} $(who -b | awk '{print $3,$4,$5}')\n"
echo -en "${green} #LVM use:${red} `sudo lvscan | gawk '{print $1}'| wc -l` uses\n"
echo -en "${green} #Connexions TCP:${red} `ss | grep tcp | wc -l | awk '{printf $1/2}'`\n"
echo -en "${green} #User log:${red} `who | wc -l`\n"
echo -en "${green} #Network:${red} IP `hostname -I` (`ip a | grep ether | awk '{print $2}'`)${nc}\n"
echo -en "${green} #Sudo: ${red} `sudo grep -c TSID /var/log/sudo/logs` cmd${nc}\n"
